<a href="https://colab.research.google.com/github/Pinky-cloud224/Integrated-scRNA-data-analysis/blob/master/Lipidation_data_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [219]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [220]:
%cd /content/drive/My Drive/

/content/drive/My Drive


In [221]:
pip install XlsxWriter

In [222]:
import pandas as pd
import xlsxwriter
data_f=pd.read_excel('lipidation_data_all_experiment_dropna.xlsx')
data_f

Unnamed: 0          id  sequence_length  \
0              0  A0A0K8P8E7              603   
1              1  A0A291NUG3              379   
2              2  A0A2T4VDM4              266   
3              3  A0A3S5YBC7              492   
4              4      A0R1E8             2111   
...          ...         ...              ...   
1895        1895      Q9HGP7              278   
1896        1896      Q9P7J9              156   
1897        1897      Q9STH5              161   
1898        1898      Q9SUC9              304   
1899        1899      Q9SUV6              142   

                                               sequence organism  \
0     M Q T T V T T M L L A S V A L A A C A G G G S ...   Others   
1     M L H S S L H P S I P Q P R G R R A K K A A F ...   Others   
2     M G L C S D P A I T Y L K R L G Y N V V R L P ...   Others   
3     M R K T V V A F A A A I A A C S A V L S S T T ...   Others   
4     M T Q N C V A P V A I I G M A C R L P G A I N ...   Others   
...                                                 ...      ...   
1895  M S P L I V G T L I I I L L S G L A T A F Y V ...   Others   
1896  M F G K V S S L L V F A S F L I I Q G A F A T ...   Others   
1897  M A Q T T T L I L L L A T L L V A A T T V S G ...   Others   
1898  M K K S L T L L I L L L C S L L F S T V L S N ...   Others   
1899  M A V A V T A V L F L A V V I A P Q W T E T K ...   Others   

          Lipidation Lipidation_Position         Annonation  
0     Palmitoylation                18,     Prosite-prorule  
1     Palmitoylation            88, 91,          similarity  
2     Palmitoylation                 4,          experiment  
3     Palmitoylation                15,     Prosite-prorule  
4     Palmitoylation                16,     Prosite-prorule  
...              ...                 ...                ...  
1895      GPI-anchor                96,   sequence analysis  
1896      GPI-anchor               129,   sequence analysis  
1897      GPI-anchor               138,   sequence analysis  
1898      GPI-anchor               282,   sequence analysis  
1899      GPI-anchor               120,   sequence analysis  

[1900 rows x 8 columns]

In [223]:
nested_list=[]
indices = data_f.iloc[0]
sequences, positions = data_f["sequence"], data_f["Lipidation_Position"]
print(range(len(sequences)))
for i in range(1900):
    sequence_i = sequences[i]
    pos = positions[i]
    pos_list = pos.split(", ")
    pos_list =[int(entry) for entry in pos_list if entry]
    labels = []
    for i in range(1, len(sequence_i.replace(" ", ""))+1):
        if i not in pos_list:
            data_f.iloc(labels.append(0))
        else:
            data_f.iloc(labels.append(1))

    nested_list.append(labels)
    #print(nested_list)

range(0, 1900)


In [224]:
nested_list_l=[]
indices = data_f.iloc[0]
sequences, positions = data_f["sequence"], data_f["Lipidation_Position"]
print(range(len(sequences)))
for i in range(1900):
    sequence_i = sequences[i]
    pos = positions[i]
    pos_list = pos.split(", ")
    pos_list =[int(entry) for entry in pos_list if entry]
    labels = []
    for i in range(1, len(sequence_i.replace(" ", ""))+1):
        if i not in pos_list:
            data_f.iloc(labels.append(0))
        else:
            data_f.iloc(labels.append(1))

    nested_list_l.append(labels)
    #print(nested_list)

range(0, 1900)


In [225]:
df=pd.DataFrame({'binary_sequence':nested_list})
print(df)

                                        binary_sequence
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
...                                                 ...
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[1900 rows x 1 columns]


In [226]:
data_f["binary_sequence"]=df
data_f

Unnamed: 0          id  sequence_length  \
0              0  A0A0K8P8E7              603   
1              1  A0A291NUG3              379   
2              2  A0A2T4VDM4              266   
3              3  A0A3S5YBC7              492   
4              4      A0R1E8             2111   
...          ...         ...              ...   
1895        1895      Q9HGP7              278   
1896        1896      Q9P7J9              156   
1897        1897      Q9STH5              161   
1898        1898      Q9SUC9              304   
1899        1899      Q9SUV6              142   

                                               sequence organism  \
0     M Q T T V T T M L L A S V A L A A C A G G G S ...   Others   
1     M L H S S L H P S I P Q P R G R R A K K A A F ...   Others   
2     M G L C S D P A I T Y L K R L G Y N V V R L P ...   Others   
3     M R K T V V A F A A A I A A C S A V L S S T T ...   Others   
4     M T Q N C V A P V A I I G M A C R L P G A I N ...   Others   
...                                                 ...      ...   
1895  M S P L I V G T L I I I L L S G L A T A F Y V ...   Others   
1896  M F G K V S S L L V F A S F L I I Q G A F A T ...   Others   
1897  M A Q T T T L I L L L A T L L V A A T T V S G ...   Others   
1898  M K K S L T L L I L L L C S L L F S T V L S N ...   Others   
1899  M A V A V T A V L F L A V V I A P Q W T E T K ...   Others   

          Lipidation Lipidation_Position         Annonation  \
0     Palmitoylation                18,     Prosite-prorule   
1     Palmitoylation            88, 91,          similarity   
2     Palmitoylation                 4,          experiment   
3     Palmitoylation                15,     Prosite-prorule   
4     Palmitoylation                16,     Prosite-prorule   
...              ...                 ...                ...   
1895      GPI-anchor                96,   sequence analysis   
1896      GPI-anchor               129,   sequence analysis   
1897      GPI-anchor               138,   sequence analysis   
1898      GPI-anchor               282,   sequence analysis   
1899      GPI-anchor               120,   sequence analysis   

                                        binary_sequence  
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                 ...  
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[1900 rows x 9 columns]

In [227]:
data_f["sequence"] = data_f["sequence"].str.replace(" ", "")

data_f.head()

Unnamed: 0          id  sequence_length  \
0           0  A0A0K8P8E7              603   
1           1  A0A291NUG3              379   
2           2  A0A2T4VDM4              266   
3           3  A0A3S5YBC7              492   
4           4      A0R1E8             2111   

                                            sequence organism      Lipidation  \
0  MQTTVTTMLLASVALAACAGGGSTPLPLPQQQPPQQEPPPPPVPLA...   Others  Palmitoylation   
1  MLHSSLHPSIPQPRGRRAKKAAFVLLSVCLVVLWDLGERPEHILQW...   Others  Palmitoylation   
2  MGLCSDPAITYLKRLGYNVVRLPREGIQPLHLLGQQRGTVEYLGSL...   Others  Palmitoylation   
3  MRKTVVAFAAAIAACSAVLSSTTTSAAPPATPITTLQADGTHLVDG...   Others  Palmitoylation   
4  MTQNCVAPVAIIGMACRLPGAINSPQQLWEALLRGDDFVTEIPTGR...   Others  Palmitoylation   

  Lipidation_Position       Annonation  \
0                18,   Prosite-prorule   
1            88, 91,        similarity   
2                 4,        experiment   
3                15,   Prosite-prorule   
4                16,   Prosite-prorule   

                                     binary_sequence  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [228]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data_f.Lipidation=le.fit_transform(data_f.Lipidation)
data_f

Unnamed: 0          id  sequence_length  \
0              0  A0A0K8P8E7              603   
1              1  A0A291NUG3              379   
2              2  A0A2T4VDM4              266   
3              3  A0A3S5YBC7              492   
4              4      A0R1E8             2111   
...          ...         ...              ...   
1895        1895      Q9HGP7              278   
1896        1896      Q9P7J9              156   
1897        1897      Q9STH5              161   
1898        1898      Q9SUC9              304   
1899        1899      Q9SUV6              142   

                                               sequence organism  Lipidation  \
0     MQTTVTTMLLASVALAACAGGGSTPLPLPQQQPPQQEPPPPPVPLA...   Others           2   
1     MLHSSLHPSIPQPRGRRAKKAAFVLLSVCLVVLWDLGERPEHILQW...   Others           2   
2     MGLCSDPAITYLKRLGYNVVRLPREGIQPLHLLGQQRGTVEYLGSL...   Others           2   
3     MRKTVVAFAAAIAACSAVLSSTTTSAAPPATPITTLQADGTHLVDG...   Others           2   
4     MTQNCVAPVAIIGMACRLPGAINSPQQLWEALLRGDDFVTEIPTGR...   Others           2   
...                                                 ...      ...         ...   
1895  MSPLIVGTLIIILLSGLATAFYVTWQGRLICAGVGLILEQAYEGGQ...   Others           0   
1896  MFGKVSSLLVFASFLIIQGAFATLVAPIGDLEHLSEIELLYTNRVL...   Others           0   
1897  MAQTTTLILLLATLLVAATTVSGQGPHIPLAPSPSVNEAMNCAAGL...   Others           0   
1898  MKKSLTLLILLLCSLLFSTVLSNLLVEPVQPNTVPAFPVETQAQSC...   Others           0   
1899  MAVAVTAVLFLAVVIAPQWTETKKPPRPSDTSDTSGTSGRDRRTMC...   Others           0   

     Lipidation_Position         Annonation  \
0                   18,     Prosite-prorule   
1               88, 91,          similarity   
2                    4,          experiment   
3                   15,     Prosite-prorule   
4                   16,     Prosite-prorule   
...                  ...                ...   
1895                96,   sequence analysis   
1896               129,   sequence analysis   
1897               138,   sequence analysis   
1898               282,   sequence analysis   
1899               120,   sequence analysis   

                                        binary_sequence  
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                 ...  
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[1900 rows x 9 columns]

In [229]:
pal_2=nested_list_l[:967]
for o_i,out in enumerate(pal_2):
    for i_i,inner in enumerate(out):
        if inner==1:
            pal_2[o_i][i_i]=2
    #print(pal_2)

In [230]:
d_f_p=pd.DataFrame({'binary_sequence_2':pal_2})
print(d_f_p)

                                     binary_sequence_2
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
..                                                 ...
962  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
963  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
964  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
965  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
966  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[967 rows x 1 columns]


In [231]:
n_myris=nested_list_l[967:1268]
d_f_n=pd.DataFrame({'binary_sequence_1':n_myris})
print(d_f_n)

                                     binary_sequence_1
0    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
..                                                 ...
296  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
297  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
298  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
299  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
300  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[301 rows x 1 columns]


In [232]:
preny_3=nested_list_l[1268:1453]
for p_i,p_out in enumerate(preny_3):
    for p_p_i,p_inner in enumerate(p_out):
        if p_inner==1:
            preny_3[p_i][p_p_i]=3
    #print(preny_3)

In [233]:
d_f_preny=pd.DataFrame({'binary_sequence_3':preny_3})
print(d_f_preny)

                                     binary_sequence_3
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
..                                                 ...
180  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
181  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
182  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
183  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
184  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[185 rows x 1 columns]


In [234]:
gpi=nested_list_l[1453:]
for gpi_in,gpi_out in enumerate(gpi):
    for gpi_i_in,gpi_i_inner in enumerate(gpi_out):
        if gpi_i_inner==1:
            gpi[gpi_in][gpi_i_in]=4
        else:
            gpi[gpi_in][gpi_i_in]=0
    #print(gpi)

In [235]:
gpi_df=pd.DataFrame({'binary_sequence_4':gpi})
print(gpi_df)

                                     binary_sequence_4
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
..                                                 ...
442  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
443  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
444  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
445  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
446  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[447 rows x 1 columns]


In [236]:
list_1=pal_2+n_myris

In [237]:
list_y_data=pd.DataFrame({'list_1_d':list_1})
print(list_y_data)

                                               list_1_d
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2     [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
...                                                 ...
1263  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1264  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1265  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1266  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1267  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[1268 rows x 1 columns]


In [238]:
list_2=preny_3+gpi

In [239]:
list_2_y_data=pd.DataFrame({'list_2_d':list_2})
print(list_2_y_data)

                                              list_2_d
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
..                                                 ...
627  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
628  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
629  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
630  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
631  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[632 rows x 1 columns]


In [240]:
all_list_y=list_1+list_2

In [241]:
y=pd.DataFrame({'y':all_list_y})
print(y)

                                                      y
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2     [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
...                                                 ...
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

[1900 rows x 1 columns]


In [242]:
data_f["binary_sequence_lipidation"]=y
data_f

Unnamed: 0          id  sequence_length  \
0              0  A0A0K8P8E7              603   
1              1  A0A291NUG3              379   
2              2  A0A2T4VDM4              266   
3              3  A0A3S5YBC7              492   
4              4      A0R1E8             2111   
...          ...         ...              ...   
1895        1895      Q9HGP7              278   
1896        1896      Q9P7J9              156   
1897        1897      Q9STH5              161   
1898        1898      Q9SUC9              304   
1899        1899      Q9SUV6              142   

                                               sequence organism  Lipidation  \
0     MQTTVTTMLLASVALAACAGGGSTPLPLPQQQPPQQEPPPPPVPLA...   Others           2   
1     MLHSSLHPSIPQPRGRRAKKAAFVLLSVCLVVLWDLGERPEHILQW...   Others           2   
2     MGLCSDPAITYLKRLGYNVVRLPREGIQPLHLLGQQRGTVEYLGSL...   Others           2   
3     MRKTVVAFAAAIAACSAVLSSTTTSAAPPATPITTLQADGTHLVDG...   Others           2   
4     MTQNCVAPVAIIGMACRLPGAINSPQQLWEALLRGDDFVTEIPTGR...   Others           2   
...                                                 ...      ...         ...   
1895  MSPLIVGTLIIILLSGLATAFYVTWQGRLICAGVGLILEQAYEGGQ...   Others           0   
1896  MFGKVSSLLVFASFLIIQGAFATLVAPIGDLEHLSEIELLYTNRVL...   Others           0   
1897  MAQTTTLILLLATLLVAATTVSGQGPHIPLAPSPSVNEAMNCAAGL...   Others           0   
1898  MKKSLTLLILLLCSLLFSTVLSNLLVEPVQPNTVPAFPVETQAQSC...   Others           0   
1899  MAVAVTAVLFLAVVIAPQWTETKKPPRPSDTSDTSGTSGRDRRTMC...   Others           0   

     Lipidation_Position         Annonation  \
0                   18,     Prosite-prorule   
1               88, 91,          similarity   
2                    4,          experiment   
3                   15,     Prosite-prorule   
4                   16,     Prosite-prorule   
...                  ...                ...   
1895                96,   sequence analysis   
1896               129,   sequence analysis   
1897               138,   sequence analysis   
1898               282,   sequence analysis   
1899               120,   sequence analysis   

                                        binary_sequence  \
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                 ...   
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                             binary_sequence_lipidation  
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2     [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...  
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                 ...  
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[1900 rows x 10 columns]

In [243]:
data_f['Annonation'].value_counts(normalize=True) * 100

sequence analysis                                31.157895
Prosite-prorule                                  19.052632
similarity                                       16.631579
experiment                                       12.000000
Unirule annotation                                7.578947
curated                                           5.000000
Similarity                                        3.894737
Manual assertionby  curator                       3.368421
sequence analysis, curated                        0.157895
Prosite-prorule, Manual assertionby curator       0.157895
manual assertionby  opinion                       0.157895
Manual assertionby curator                        0.105263
experiment                                        0.105263
by similarity                                     0.105263
Prosite-prorule-annotation                        0.105263
Manual assertionby  similarity                    0.105263
similarity                                        0.0526

In [244]:
test=data_f.query("Annonation=='experiment'")
test

Unnamed: 0          id  sequence_length  \
2              2  A0A2T4VDM4              266   
11            11      B2RHG2              324   
22            22      G5EBX9              707   
28            28      J7QLC0             1706   
30            30      O00161              211   
...          ...         ...              ...   
1677        1677      Q8LD43               62   
1683        1683      Q9C8A4               58   
1689        1689      Q9LYF6               61   
1691        1691      Q9M373               74   
1821        1821      Q9GP84              155   

                                               sequence organism  Lipidation  \
2     MGLCSDPAITYLKRLGYNVVRLPREGIQPLHLLGQQRGTVEYLGSL...   Others           2   
11    MNKRKHMDIRRLIISLPAIMALWGGLASCDKMIYDNYDDCPRGVYV...   Others           2   
22    MGCGPSSGRQNPSTELKKSTRATTTTTSSSQRNNYNDNNQNTSSSS...   Others           2   
28    MQQSHQAGYANAADRESGIPAAVLDGIKAVAKEKNATLMFRLVNPH...   Others           2   
30    MDNLSSEEIQQRAHQITDESLESTRRILGLAIESQDAGIKTITMLD...   Others           2   
...                                                 ...      ...         ...   
1677  MEMKNIFVALFISAVLVSSVSAATMESPAPSPGASSASTVAFPVVG...   Others           0   
1683  MEAMKMKMMVFIMVVAVAFSAATAATVEAPAPSPTSDAAMFVPALF...   Others           0   
1689  MAISKASIVVLMMVIISVVASAQSEAPAPSPTSGSSAISASFVSAG...   Others           0   
1691  MASRNSVAVIALFAFVFAVISPFAGAQSLAPAPSPTSDGTSIDQGI...   Others           0   
1821  MRFISIFLIIVALCVSSSWAFNFTDQPNSFRISGTGCGSGTTTVYF...   Others           0   

            Lipidation_Position  Annonation  \
2                           4,   experiment   
11                         29,   experiment   
22                          3,   experiment   
28                   860, 983,   experiment   
30    79, 80, 83, 85, 87, 112,   experiment   
...                         ...         ...   
1677                       35,   experiment   
1683                       36,   experiment   
1689                       35,   experiment   
1691                       37,   experiment   
1821                      133,   experiment   

                                        binary_sequence  \
2     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
11    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
22    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
28    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
30    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                 ...   
1677  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1683  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1689  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1691  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1821  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                             binary_sequence_lipidation  
2     [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
11    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
22    [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
28    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
30    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                 ...  
1677  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1683  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1689  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1691  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1821  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[228 rows x 10 columns]

In [245]:
test_x=test["binary_sequence"]
test_y=test["binary_sequence_lipidation"]

In [246]:
train = data_f.drop(data_f[(data_f.Annonation=="experiment")].index)
train

Unnamed: 0          id  sequence_length  \
0              0  A0A0K8P8E7              603   
1              1  A0A291NUG3              379   
3              3  A0A3S5YBC7              492   
4              4      A0R1E8             2111   
5              5      A1A5H8              546   
...          ...         ...              ...   
1895        1895      Q9HGP7              278   
1896        1896      Q9P7J9              156   
1897        1897      Q9STH5              161   
1898        1898      Q9SUC9              304   
1899        1899      Q9SUV6              142   

                                               sequence organism  Lipidation  \
0     MQTTVTTMLLASVALAACAGGGSTPLPLPQQQPPQQEPPPPPVPLA...   Others           2   
1     MLHSSLHPSIPQPRGRRAKKAAFVLLSVCLVVLWDLGERPEHILQW...   Others           2   
3     MRKTVVAFAAAIAACSAVLSSTTTSAAPPATPITTLQADGTHLVDG...   Others           2   
4     MTQNCVAPVAIIGMACRLPGAINSPQQLWEALLRGDDFVTEIPTGR...   Others           2   
5     MGCVKSKEDKGPTQKYRPDPTNPTPGSHMGLYGPDPTQMGQSPALK...   Others           2   
...                                                 ...      ...         ...   
1895  MSPLIVGTLIIILLSGLATAFYVTWQGRLICAGVGLILEQAYEGGQ...   Others           0   
1896  MFGKVSSLLVFASFLIIQGAFATLVAPIGDLEHLSEIELLYTNRVL...   Others           0   
1897  MAQTTTLILLLATLLVAATTVSGQGPHIPLAPSPSVNEAMNCAAGL...   Others           0   
1898  MKKSLTLLILLLCSLLFSTVLSNLLVEPVQPNTVPAFPVETQAQSC...   Others           0   
1899  MAVAVTAVLFLAVVIAPQWTETKKPPRPSDTSDTSGTSGRDRRTMC...   Others           0   

     Lipidation_Position         Annonation  \
0                   18,     Prosite-prorule   
1               88, 91,          similarity   
3                   15,     Prosite-prorule   
4                   16,     Prosite-prorule   
5                    3,          similarity   
...                  ...                ...   
1895                96,   sequence analysis   
1896               129,   sequence analysis   
1897               138,   sequence analysis   
1898               282,   sequence analysis   
1899               120,   sequence analysis   

                                        binary_sequence  \
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...   
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
5     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                 ...   
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                             binary_sequence_lipidation  
0     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, ...  
4     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
5     [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
...                                                 ...  
1895  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1896  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1897  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1898  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1899  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[1672 rows x 10 columns]

In [247]:
train_dataset_X=train['binary_sequence']
train_dataset_y=train['binary_sequence_lipidation']

In [248]:
from torch import Tensor
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader

In [249]:
def ints_to_tensor(ints):
  if isinstance(ints,torch.Tensor):
    return ints
  if isinstance(ints[0],int):
    return torch.LongTensor(ints)
  if isinstance(ints[0],torch.Tensor):
    return pad_tensors(ints)
  if isinstance(ints[0],list):
    return ints_to_tensor([ints_to_tensor(inti) for inti in ints])

In [250]:
def pad_tensors(tensors):
  rep=tensors[0]
  padded_dim=[]
  for dim in range(rep.dim()):
    max_dim=max([tensor.size(dim) for tensor in tensors])
    padded_dim.append(max_dim)
  padded_dim=[len(tensors)]+padded_dim
  padded_tensor=torch.zeros(padded_dim)
  padded_tensor=padded_tensor.type_as(rep)
  for i, tensor in enumerate(tensors):
    size=list(tensor.size())
    if len(size)==1:
      padded_tensor[i, :size[0]]=tensor
    elif len(size)==2:
      padded_tensor[i, :size[0], :size[1]]=tensor
    elif len(size)==3:
      padded_tensor[i, :size[0], :size[1], :size[2]]=tensor
    else:
      raise ValueError('padding is......')
  return padded_tensor


In [251]:
X_t_train=ints_to_tensor(train_dataset_X)
X_t_train

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [252]:
X_t_train = X_t_train.to(torch.float32)
X_t_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [253]:
y_t_train=ints_to_tensor(train_dataset_y)
y_t_train

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [254]:
y_t_train = y_t_train.to(torch.float32)
y_t_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [255]:
test_x = torch.LongTensor(list(map(lambda x: x + [0] * (max(map(len, test_x)) - len(x)), test_x)))

In [256]:
test_x

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [257]:
X_test = test_x.to(torch.float32)
X_test

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [258]:
test_y = torch.LongTensor(list(map(lambda x: x + [0] * (max(map(len, test_y)) - len(x)), test_y)))
test_y

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 2,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [259]:
y_test = test_y.to(torch.float32)
y_test

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 2.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [260]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X_t_train,y_t_train,test_size=0.1,random_state=8)

In [261]:
X_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [262]:
X_val

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [263]:
y_train

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [264]:
y_val

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [265]:
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler

In [266]:
###class weighting
labels_unique,counts=np.unique(train['Lipidation'],return_counts=True)
print("Unique labels: {}".format(labels_unique))

Unique labels: [0 1 2 3]


In [267]:
class_weights = 1./torch.tensor(counts,dtype=torch.float32)
class_weights

tensor([0.0024, 0.0047, 0.0011, 0.0068])

In [268]:
weighted_sampler = WeightedRandomSampler(
    weights=class_weights,
    num_samples=len(class_weights),
    replacement=True
)

In [269]:
class ClassifierDataset(Dataset):

    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]

    def __len__ (self):
        return len(self.X_data)


train_dataset = ClassifierDataset(X_train,y_train)
val_dataset=ClassifierDataset(X_val,y_val)
test_dataset=ClassifierDataset(X_test,y_test)

In [270]:
EPOCHS = 300
BATCH_SIZE = 64
LEARNING_RATE = 0.01
NUM_FEATURES = 1
NUM_CLASSES = 5

In [271]:
train_loader = DataLoader(dataset=train_dataset,
                          batch_size=BATCH_SIZE,
                          sampler=weighted_sampler
)

In [274]:
val_loader=DataLoader(dataset=val_dataset,batch_size=BATCH_SIZE,sampler=weighted_sampler)
test_loader=DataLoader(dataset=test_dataset,batch_size=BATCH_SIZE,sampler=weighted_sampler)

In [275]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [276]:
import torch
print(torch.Tensor(1).dtype)

torch.float32


In [277]:
import torch.nn as nn
import torch.optim as optim

In [278]:
class FeedforwardNeuralNetModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(FeedforwardNeuralNetModel, self).__init__()
        # Linear function
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        # Non-linearity
        self.tanh = nn.Tanh()
        self.relu = nn.ReLU()
        # Linear function (readout)
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        # Linear function
        out = self.fc1(x)
        # Non-linearity
        out = self.tanh(out)
        out=self.relu(out)
        # Linear function (readout)
        out = self.fc2(out)
        return out
'''
STEP 4: INSTANTIATE MODEL CLASS
'''
input_dim = 3971
hidden_dim = 100
output_dim = 5

model_n = FeedforwardNeuralNetModel(input_dim, hidden_dim, output_dim)

In [279]:
model_n.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_n.parameters(), lr=LEARNING_RATE)
print(model_n)


FeedforwardNeuralNetModel(
  (fc1): Linear(in_features=3971, out_features=100, bias=True)
  (tanh): Tanh()
  (relu): ReLU()
  (fc2): Linear(in_features=100, out_features=5, bias=True)
)


In [280]:
for X_train_batch,y_train_batch in train_loader:
    print(X_train_batch.to(device))

tensor([[0., 1., 1.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 0., 0., 0.]])


In [289]:
X_train_batch.size(dim=1)

3971

In [290]:
y_train_batch.size(dim=1)

3971

In [281]:
torch.flatten(y_train_batch)

tensor([0., 2., 2.,  ..., 0., 0., 0.])

In [282]:
y_train_pred = model_n(X_train_batch)
y_train_pred

tensor([[ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444],
        [ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444],
        [ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444],
        [ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444]],
       grad_fn=<AddmmBackward0>)

In [283]:
model_n(X_train_batch.to(device))[:3]

tensor([[ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444],
        [ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444],
        [ 0.0789, -0.0657, -0.0300, -0.0748,  0.0444]],
       grad_fn=<SliceBackward0>)

In [284]:
model_n(X_train_batch.to(device))[0].shape, NUM_CLASSES

(torch.Size([5]), 5)

In [285]:
for X_val_batch,y_val_batch in val_loader:
    print(X_val_batch.to(device))

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [286]:
def multi_acc(y_pred, y_test):
    y_pred_softmax = torch.log_softmax(y_pred, dim = 1)
    _, y_pred_tags = torch.max(y_pred_softmax, dim = 1)

    correct_pred = (y_pred_tags == y_test).float()
    acc = correct_pred.sum() / len(correct_pred)

    acc = torch.round(acc * 100)

    return acc

In [287]:
accuracy_stats = {
    'train': [],
    "val": []
}
loss_stats = {
    'train': [],
    "val": []
}

In [291]:
from tqdm.notebook import tqdm
print("Begin training.")
for e in tqdm(range(1, EPOCHS+1)):

    # TRAINING
    train_epoch_loss = 0
    train_epoch_acc = 0
    model_n.train()
    for X_train_batch, y_train_batch in train_loader:
        X_train_batch, y_train_batch = X_train_batch.to(device), y_train_batch.to(device)
        optimizer.zero_grad()

        y_train_pred = model_n(X_train_batch)
        train_loss = criterion(y_train_pred, torch.flatten(y_train_batch))
        train_acc = multi_acc(y_train_pred, y_train_batch)

        train_loss.backward()
        optimizer.step()

        train_epoch_loss += train_loss.item()
        train_epoch_acc += train_acc.item()

Begin training.


  0%|          | 0/300 [00:00<?, ?it/s]

ValueError: ignored

In [292]:
y_train_pred.size(dim=1)

5

In [293]:
y_train_batch.size(dim=1)

3971